### ISSUE TITLE
Is it correct that netlify.app is on the list?

### ISSUE THREAD

**Issue by will-j-c** [phantom-labs/blocklist#186]
Hi everyone

I had the error pop up when trying to open my non-blockchain related app on Netlify. Checking down the list, I notice that netlify.app has been added. 

Given Netlify is a popular hosting service for front-end apps of all sorts, is it right that the entire netlify.app domain part is included on the list? Especially in a dev environment, using the Netlify autogenerated URL is standard practice.

Thanks

**Comment by puneetkaura** [comment]
Don't think so, having domains used by platforms like Netlify, Vite does more harm than good

**Comment by Harii94** [comment]
Recently there is an increase in scammers using a subdomain for malicious practices. The website has been removed from the block list.
