### ISSUE TITLE
Phantom blocks sneks.gg, the legitimate URL for The Sneks project.

### ISSUE THREAD

**Issue by Spongled** [phantom-labs/blocklist#2]
![ss (chrome_2021-11-16 at 01-30-03](https://user-images.githubusercontent.com/27869072/141879375-060de37b-46e9-440b-80fb-b66ee2a7705b.png)

https://sneks.gg is the legitimate domain for The Sneks project (https://twitter.com/solsneks). We have a mint upcoming very soon, and it's of the utmost important this is resolved quickly!

Thanks!

**Comment by AlwaysBCoding** [comment]
Hey, thanks for bringing this up, I have no idea why this url was on the initial blocklist if it's the legitimate domain, but I can fix this now.

**Comment by Spongled** [comment]
@AlwaysBCoding Thanks Jordan, please let me know as soon as it's resolved :)

**Comment by AlwaysBCoding** [comment]
@Spongled this should be resolved. Again, extremely sorry about that. We've been aggregating a list of phishing sites that have come through our support channel for the past couple weeks and have no idea how that got onto the list.

Thanks again for bringing this to our attention.

**Comment by Spongled** [comment]
@AlwaysBCoding No worries, thanks for sorting it so promptly!
