### ISSUE TITLE
nft-blocklist.yaml?

### ISSUE THREAD

**Issue by dbnewman** [phantom-labs/blocklist#301]
Hi,

I can't see any documentation on this, is this working - if so, how does it work?

We are dealing with quite a few scam NFT's with the Tomorrowland project.

Thanks.

**Comment by Helpcenter101** [comment]
We'd be happy to look into this for you
Kindly file a support ticket below 
https://forms.gle/Lafx8qFvBGEYKZ677

**Comment by Harii94** [comment]
Hey, 
You can report them to our support team. Visit the Phantom help center and click on the chat icon at the bottom right > type in "Report scam NFTs" and follow the instructions to submit a report. 
### Steps to visit the Phantom support site:
Phantom.app > Click on the Support section at the top (or) In your Wallet Settings >Click on "About Phantom" > Help & Support.
