### ISSUE TITLE
Question about a token that is massivly airdropped

### ISSUE THREAD

**Issue by loucaslt** [phantom-labs/blocklist#349]
Hello @Harii94,

Since a while, there is a "FLIP.GG" Token that is airdropped to many NFT Collection hosted on MagicEden.
Token Id: https://solscan.io/token/VVWAy5U2KFd1p8AdchjUxqaJbZPBeP5vUQRZtAy8hyc

There is 145,756 holders, and it keep have many more as they do airdropping of it regularly. This token promote a flipping website, but there is no way to find if this real of not. We've many report from people annoyed by this airdrop.

What would you suggest to do? Create a PR to add the token only in the blocklist?

**Comment by Harii94** [comment]
@loucaslt Currently the blocklist doesn't support Fungibles. We will work on something to control these spam tokens in the future. For now, you can use the "manage token list" option to hide them from the assets tab. If these spam tokens turn out to be scamming people, you can report it to our support team.
