### ISSUE TITLE
New Scam WebSites

### ISSUE THREAD

**Issue by Alex926462** [phantom-labs/blocklist#360]
apocalypse.city
celadongame.com
moonwallet.io

apocalypse and celadon already blocked, it’s new domains. MoonWallet - scam wallet, stealer.

all have link on stealer on website.

**Comment by Harii94** [comment]
Can you please provide additional info on moonwallet.io? I am not able to validate it as a scam.

**Comment by Alex926462** [comment]
> Can you please provide additional info on moonwallet.io? I am not able to validate it as a scam.

https://www.dropbox.com/s/dl/guujl00e9mpahsb/moonwallet-1.39.0-2839.exe

link from website. This launcher upload stealer. 

![A86BA126-E0EE-4587-B3E0-8C1D22606A95](https://user-images.githubusercontent.com/121979386/216262169-5e822e5d-1500-4749-b03f-23a00933c556.jpeg)

**Comment by Harii94** [comment]
added!
