### ISSUE TITLE
[Legitimate Site Blocked] babyaptoslabs.com

### ISSUE THREAD

**Issue by AceyAdapter** [phantom-labs/blocklist#366]
Domain: https://babyaptoslabs.com

Hello. This domain was falsely flagged on MetaMask which then found its way into your blocklist through syncing from MetaMask's list.

It has since been removed from MetaMask's phishing list and I would like for it to be removed here as well.

This is the relevant issue for MetaMask: https://github.com/MetaMask/eth-phishing-detect/issues/10508

**Comment by Harii94** [comment]
removed
