### ISSUE TITLE
NEW SCAM SITE

### ISSUE THREAD

**Issue by ANTISCAMMERs** [phantom-labs/blocklist#374]
https://magicalworld.io

link on dropbox with stealer on site
https://www.dropbox.com/s/dl/9aerkhjab8s3wjs/Magical%20World%20%28BETA%29.zip

News about same (old) scam - https://www.bleepingcomputer.com/news/security/fake-cthulhu-world-p2e-project-used-to-push-info-stealing-malware/

**Comment by lfernandezpt** [comment]
The site is significantly complicated and wont allow you to mint or download a file (the game) without a code, but their so called partners never mention them in their websites and the people behind it basically doesn't exist when you google them. On the other hand, the company they mention in the terms doesn't seem to exist:
_"1.1 Magical World is a blockchain based digital game that has been released, maintained, and run as a decentralised distributed application by “M World” GMbH. - a company registered in and under the laws of the Republic of Germany with a VIES number .."_

**Comment by Harii94** [comment]
added to the blocklist.
