### ISSUE TITLE
NEW SCAM SITE

### ISSUE THREAD

**Issue by ANTISCAMMERs1** [phantom-labs/blocklist#380]
https://magicalworld.cool/

link on dropbox with stealer on site
https://www.dropbox.com/s/dl/9aerkhjab8s3wjs/Magical%20World%20%28BETA%29.zip

News about same (old) scam - https://www.bleepingcomputer.com/news/security/fake-cthulhu-world-p2e-project-used-to-push-info-stealing-malware/

**Comment by Harii94** [comment]
added, thank you!
